version: "3.3"
services:
  chunk_service:
    build:
      context: ./chunk_service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./chunk_service:/code
    environment:
      FLASK_ENV: development

  speech_service:
    build:
      context: ./speech_process
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./speech_service:/code
    environment:
      FLASK_ENV: development
